### ISSUE TITLE
您好！如何和已有业务结合呢

### ISSUE THREAD

**Issue by shengke90** [uptop/JavaWebSocket#1]
项目已经成功运行了，如何和已有业务结合呢！比如有个提交评论的业务，我如何在业务里调用WebSocket通知已关注的人呢

**Comment by uptop** [comment]
服务器消息转发是通过sessionID实现的，每一个通过websocket连接服务器的用户都有一个sessionID，记录该ID，当需要推送时，找到该ID即可。

**Comment by shengke90** [comment]
@uptop 谢谢！使用传参数已经实现对不同用户组里的用户群发消息通知了！
